# Info
name: framework.cufy.org
title: Cufy Framework
email: framework@cufy.org
description: >-
  The main project on the cufy organization. It is written in java.
  It tries to compete with other java frameworks. Cufy framework focuses on
  inheritance and reflection, making it more reliable in big complex projects.
  The framework still not completely ready to be used in big projects since it
  still in the beta stage. Cufy Framework have been divided onto different packages,
  each package limited to access specific packages only and each package have different purpose.

# GitHub
github:
  is_project_page: true
  repository_url: https://github.com/cufyorg/framework
  owner_url: https://github.com/cufyorg
  owner_name: Cufy

# Collections
collections:
  fragments:
  pages:
    output: true

# Build
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      favicon: '/assets/logo/cufy.ico'
      title: 'Cufy Framework'